### ISSUE TITLE
Running Ruby Code - Possible typo

### ISSUE THREAD

**Issue by barnold804** [learn-co-curriculum/phase-3-running-ruby-code#11]
### Canvas Link

https://learning.flatironschool.com/courses/4994/assignments/172888?module_item_id=376781

### Concern

I found what looks to be a typo in the lesson:

"Ruby several methods for printing output to the terminal: puts, print, p, and pp."

### Suggested Changes

Should it be the following?

"Ruby (offers/has) several methods for printing output to the terminal: puts, print, p, and pp."

**Comment by lizbur10** [comment]
Hi there! Thanks for spotting this issue and providing feedback.

This has now been fixed. Note, however, that if you are working in Canvas the
changes may not show up there, but they will for future students.

Thanks again for contributing to the Flatiron School curriculum 💙
